version: '3.8'

services:
  gaianet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gaianet_node
    restart: unless-stopped
    ports:
      - "3003:3001"  # Map host port 3030 to container port 3030